### ISSUE TITLE
Kernel BatterySaver setting being ignored after some time.

### ISSUE THREAD

**Issue by ixende** [freak07/Kirisakura_ANAKIN_ROG5#3]
Happened on 
2.1.4 running 31.0810.1226.128
And 2.2.0 running 31.0810.1226.139

EXKM battery saver settings will be lost after a period of use, happened again today with about 18h of phone runtime.
CPU frequency will not remain at set batterysaver settings, and bettery drain will be much higher. Changing any setting will not re-enable the setting. Only a phone reboot will work.
![Screenshot_20230127-121755697](https://user-images.githubusercontent.com/123910754/215365259-c1882f59-a4ed-4639-bf64-041d9d60812e.jpg)

**Comment by freak07** [comment]
It's the thermal daemon getting stuck , so unrelated to the kernel. Asus needs to fix it, I can reproduce it on stock kernel as well.

It happens if the phone warms up and is put to sleep while it's still thermally throttled.

**Comment by freak07** [comment]
solved in latest release, by reverting qcom code that´s also in asus stock kernel
