### ISSUE TITLE
How do I build the kernel myself?

### ISSUE THREAD

**Issue by jbro129** [freak07/Kirisakura_ANAKIN_ROG5#4]
Hello, I am having some trouble building the kernel. Every time I try to build I get a different error even though I have not changed any of the source. Basically all I am trying to do is add KernelSU to the kernel. I have tried compiling your fork as well as the official Asus Rog 5s kernel source, but I come across the same issues.

I am using Ubuntu 22.04.3 LTS with WSL in windows to compile . I run `make menuconfig` then `make kernel` to try to build it.

Here is the make output when I try to compile: 
```
CALL    scripts/checksyscalls.sh
CALL    scripts/atomic/check-atomics.sh
/bin/sh: 1: ./scripts/gcc-wrapper.py: not found
  DESCEND  objtool
/bin/sh: 1: ./scripts/gcc-wrapper.py: not found
/bin/sh: 1: ./scripts/gcc-wrapper.py: not found
  CC      kernel/sched/rt.o
b'kernel/sched/rt.c: In function \xe2\x80\x98task_may_not_preempt\xe2\x80\x99:\n' b'kernel/sched/rt.c:1535:26: error: implicit declaration of function \xe2\x80\x98__IRQ_STAT\xe2\x80\x99; did you mean \xe2\x80\x98IPC_STAT\xe2\x80\x99? [-Werror=implicit-function-declaration]\n' b' 1535 |                          __IRQ_STAT(cpu, __softirq_pending);\n' b'      |                          ^~~~~~~~~~\n' b'      |                          IPC_STAT\n' b'kernel/sched/rt.c:1535:42: error: \xe2\x80\x98__softirq_pending\xe2\x80\x99 undeclared (first use in this function); did you mean \xe2\x80\x98or_softirq_pending\xe2\x80\x99?\n' b' 1535 |                          __IRQ_STAT(cpu, __softirq_pending);\n' b'      |                                          ^~~~~~~~~~~~~~~~~\n' b'      |                                          or_softirq_pending\n' b'kernel/sched/rt.c:1535:42: note: each undeclared identifier is reported only once for each function it appears in\n' b'kernel/sched/rt.c:1540:41: error: \xe2\x80\x98struct thread_info\xe2\x80\x99 has no member named \xe2\x80\x98preempt_count\xe2\x80\x99\n' b' 1540 |                  (task_thread_info(task)->preempt_count\n' b'      |                                         ^~\n' b'kernel/sched/rt.c:1542:1: error: control reaches end of non-void function [-Werror=return-type]\n' b' 1542 | }\n' b'      | ^\n' b'cc1: some warnings being treated as errors\n' make[2]: *** [scripts/Makefile.build:288: kernel/sched/rt.o] Error 1
make[1]: *** [scripts/Makefile.build:558: kernel/sched] Error 2
make: *** [Makefile:1907: kernel] Error 2
```

Every time I try to compile I get something along the lines of that. My guess is that it has something to do with `/bin/sh: 1: ./scripts/gcc-wrapper.py: not found`. I checked the scripts folder and gcc-wrapper.py does exist.

Maybe I just can't compile it from wsl? Please let me know, thank you.

**Comment by jbro129** [comment]
After some further investigation I found 'build_kirisakura.sh'. I downloaded aarch64-linux-android-4.9, arm-linux-androideabi-4.9, dtc, and clang from Googles source and modified the file to include them. 
After a long build and lots of output I get `make: *** [Makefile:190: sub-make] Error 2`

I scroll up and I see: 
```
../techpack/audio/soc/pinctrl-wcd.c:19:10: fatal error: 'pinctrl-utils.h' file not found
#include "pinctrl-utils.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
```
The file does exist as a symlink.

**Comment by freak07** [comment]
> After some further investigation I found 'build_kirisakura.sh'. I downloaded aarch64-linux-android-4.9, arm-linux-androideabi-4.9, dtc, and clang from Googles source and modified the file to include them. After a long build and lots of output I get `make: *** [Makefile:190: sub-make] Error 2`
> 
> I scroll up and I see:
> 
> ```
> ../techpack/audio/soc/pinctrl-wcd.c:19:10: fatal error: 'pinctrl-utils.h' file not found
> #include "pinctrl-utils.h"
>          ^~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> The file does exist as a symlink.

make sure the repo you´re building in is placed as the symlink requires:

https://github.com/freak07/Kirisakura_ANAKIN_ROG5/blob/master_release_t_1/techpack/audio/soc/pinctrl-utils.h

path/to/your/repo/kernel/msm-5.4/actual_source_from_this_repo
